### ISSUE TITLE
Make sure sbbadger doesn't fall all if pydot isn't present

### ISSUE THREAD

**Issue by hsauro** [sys-bio/SBbadger#2]
SBbadger should be able to continue working if pydot is not installed.  

I note from the pydot GitHub page that graphviz has to be installed separately and doesn't come with pydot. Since most people won't have graphviz installed it's important that sbbadger can deal with that by just ignoring any drawing command but can still generate random networks.

**Comment by mialko** [comment]
A couple points 

- A version of graphviz appears to come bundled with pydot when installing via conda.
- pip will install pydot whether graphviz is installed or not. It will of course fail if the argument `net_plots=True`.

I have made an update such that:

- Importation of pydot is skipped if it is not installed.
- If `net_plots=True` and pydot is not installed network plot generation is ignored but the models are still generated.
