### ISSUE TITLE
Add new method to returna single network

### ISSUE THREAD

**Issue by hsauro** [sys-bio/SBbadger#4]
Currently, all generated models are saved to a directory, requiring the user to find the directory and load any of the models they would like to look at. which for a single model can be an unnecessary burden for the user. To make things easier add a new method:

generate.model()

where it only generates a single model and returns the model as a string to the user, eg

antStr = generate.model (format='antimony')

sbmlStr = generate.model (format='sbml')

I imagine the default would be 'ant'. The arguments to model() will be the same as models() expect that n_models  = 1 and can't be changed to another value.

**Comment by mialko** [comment]
Can now be done with the generate.model method.
